algoritmo "area do terreno"

// Autor : Caline Myrella
// Data : 13/04/2026
// Seção de Declarações 
var

   comp,larg, final: real
inicio

      escreval ("Vamos calcular a area do terreno retangular")
      escreval ("digite o valor da largura")
      leia (larg)
      
      escreva ("Digite o valor do comprimento")
      leia (comp)
      
      final <- larg * comp
      
      escreval ("O valor da área do terreno é", final)
      

fimalgoritmo
